### PR TITLE
Add accessible datepicker to ReportGenerator

### PR DESCRIPTION
**Pull request by RyanMcG**
Upgrades jQuery from 1.4.4 to 1.7.2 and adds the accessible datepicker.

### CODE REVIEW

**Comment by RyanMcG** [comment]
@peterdietz Hey, have you looked at this yet?

**Comment by peterdietz** [comment]
Looks good to me.

**Comment by peterdietz** [comment]
Hi @RyanMcG, I've noticed a regression with the date picker. Its not formatting the date properly. 
The date picker will paste: 1/1/2008
But report generator wants ISO-8601 values, such as: 2008-01-01

**Comment by RyanMcG** [comment]
@peterdietz it makes sense to fix this server side to allow for any recognizable date formats. I'll look into it tomorrow.

**Pull request merged**
